### ISSUE TITLE
"The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256."

### ISSUE THREAD

**Issue by ArnaudTarroux** [wladislavk/S3UploaderBundle#1]
Hi !
Is it possible to update the bundle to update the authorization mechanism to AWS4-HMAC-SHA256 ?

Thank you  :)

**Comment by wladislavk** [comment]
Maybe so. Is it mandatory for new S3 instances?

**Comment by ArnaudTarroux** [comment]
Thank you for the reply, it is mandatory for certains region in my case : eu-central-1
